### ISSUE TITLE
Rank order?

### ISSUE THREAD

**Issue by issyrocks12** [MilkBowl/Vault#624]
I am using permissionsEX and coloredtags. For some reason it isn't using the proper rank order. I have tested the rank order by using /pex promote. I also had this problem with group manager and other rank order displaying things. I am running vault 1.5.6, does it store rank orders? If so how can I reset this order?

**Comment by Sleaker** [comment]
Vault is a passive plugin that only provides connectors to various permission/economies.  It does not store any ranks, or specific ordering. If you're having ordering issues with ranks it's most likely because they are not setup properly to function with whatever plugin you're trying to use to manage them. Vault does not provide any facilities to handle promotions/demotions it simply returns a list of groups the player has, or a list of groups setup on the server. How these are returned is based on your configuration in the actual permission plugin.
