### ISSUE TITLE
zPermissions 1.2a and Vault 1.5.6

### ISSUE THREAD

**Issue by UnioDex** [MilkBowl/Vault#625]
Im still using zPermissions 1.2a in my 1.8.8 server. Because my server is not in online-mode and zPermissions 1.3 wants online uuids. Im still using Vault 1.4.1 in my 1.8.8 spigot server. I want update Vault but Vault 1.5.6 does not support zPermissions. Can you add zPermissions 1.2 support again?

**Comment by Sleaker** [comment]
zPermissions connector was removed from Vault because zPermissions provides it's own connector that handles everything properly.  If it is non-functional for the 1.3 version you will need to bring that up or have someone patch it as it was the latest version already:

https://github.com/ZerothAngel/zPermissions/blob/master/src/main/java/org/tyrannyofheaven/bukkit/zPermissions/vault/VaultPermissionBridge.java
