### ISSUE TITLE
Privileges Dependency cant be resolved

### ISSUE THREAD

**Issue by seyfahni** [MilkBowl/Vault#633]
[krinsoft] (http://krinsoft.net/) [reposetory] (http://ci.krincraft.net/plugin/repository/everything/) is down.
Maven Repository:
```
		<repository>
			<id>krinsoft</id>
			<url>http://ci.krincraft.net/plugin/repository/everything/</url>
		</repository>
```
Maven Dependency:
```
		<dependency>
			<groupId>net.krinsoft</groupId>
			<artifactId>Privileges</artifactId>
			<version>1.8.1</version>
			<optional>true</optional>
		</dependency>
```
This results in build failure.

**Comment by Sleaker** [comment]
I'm aware. thanks for reminding me though.

**Comment by seyfahni** [comment]
How do you build Vault then? No clean builds? Adding the dependency manually? Is there a possibility of downloading it? Or should I just remove the classes and its dependencies?

**Comment by Sleaker** [comment]
The fix is to download the dependency manually stuff it into the libs directory, then change the pom to point at the local copy instead.  I've got a new build incoming with this completed so it'll be building now. For the most part though, you shouldn't need dev versions of Vault, there's no functional purpose to adding content to it. Fixes for the Item lookups are in Vault API, and all new Vault hooks should be put into their implementation plugins

**Comment by seyfahni** [comment]
Sorry, but I can't figure out how to add my economy plugin to be supported by Vault without adding it to this project. If there is another way, tell me please.
