### ISSUE TITLE
Hooking my own permissions engine into vaultapi

### ISSUE THREAD

**Issue by theresajayne** [MilkBowl/Vault#684]
I have in the past managed to hook my own economy plugin to vault using the Economy interface but there is no interface available for chat or permissions and as you have said you will not add any more plugins to vault how do we add permissions support to our plugin without changing vault?

**Comment by theresajayne** [comment]
Let me correct that we have implemented our own permissions system and want vault to use it

**Comment by Sleaker** [comment]
Since you've already done this for your own Economy, it should be fairly trivial to get it up and running for Perms/Chat API hooks. You must have just missed where the interfaces are located:

https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/permission/Permission.java

https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/chat/Chat.java

 - Hope that all helps.
