### ISSUE TITLE
Possible implementation/addition of support of BigDecimals

### ISSUE THREAD

**Issue by luwie556** [MilkBowl/Vault#741]
Hey i was wondering if you would implement bigdecimals which would make it so people can have > 10 Trillion which people have done before but I'm thinking with a custom fork of Vault. But if you're asking why the large inflation, which the answer would be OP servers, such as OP Prison (Big inflation leader)

**Comment by Sleaker** [comment]
This has been discussed in length in the past and will not be added.

**Comment by Lightning11wins** [comment]
Is there a way I can make sure that if someone gets this much money there will not be any glitches/errors? That could be very confusing and create a big mess.

**Comment by Sleaker** [comment]
@Lightning11wins that's not a question for Vault. check with your economy plugin on the limitations.

**Comment by Lightning11wins** [comment]
So if someone gets that much money with vault, what will happen when they get, say another 25$?

**Comment by Sleaker** [comment]
@Lightning11wins  - Money isn't 'gotten with vault' - Vault just defines the API. If your economy backend uses BigDecimal and another plugin performs a give player X $25 then it'll work just fine, as the number '25' is well within precision handling for a double. The point of using bigdecimal only becomes a potential issue when plugins want to transfer large amounts of $ at once between accounts. Since the methods by which Vault defines it's layer uses doubles there may be som precision loss for very large numbers or numbers with significant decimals of precision, but this is
