### ISSUE TITLE
Issue attempting to check for latest version

### ISSUE THREAD

**Issue by srnyx** [MilkBowl/Vault#808]
Not sure if this is vault or not

Paper-Spigot 1.14.4, latest plugin version
**Go to lines 854-880**
https://pastebin.com/2caQtJgb

**Comment by Sleaker** [comment]
You have a network issue it seems there's a ton of other stuff erroring in here. Vault checks bukkit.org for updates, not api.connorlinfoot.com - it also supresses any form of http connection failures because they're not useful.

https://github.com/MilkBowl/Vault/blob/2a85b772efaa196556f11dff92c352ae09461c55/src/net/milkbowl/vault/Vault.java#L552

that's the code block that checks for updates. You can verify this in your logfile by matching the numeric log statements with the plugins Vault shows as 22 in your logfile.
