### ISSUE TITLE
1.18 Compatibility?

### ISSUE THREAD

**Issue by makcuber** [MilkBowl/Vault#870]
Im sure this is being looked at but since I didnt see any open issue for this, is compatibility for 1.18 being worked on or tested?

**Comment by Strahilchu** [comment]
I'm having issues with Vault in 1.18.1

**Comment by Sleaker** [comment]
@makcuber if you have a valid issue please feel free to re-open this with a report of what is not working with 1.18. As it looks there was no change to the service registration in the bukkit API.

**Comment by makcuber** [comment]
> @makcuber if you have a valid issue please feel free to re-open this with a report of what is not working with 1.18. As it looks there was no change to the service registration in the bukkit API, so there Vault will just work as-is.

@Sleaker If its been confirmed to be working with 1.18 by the dev team then why is the documentation not up to date on the Spigot page and/or the readme file? A quick 5min edit of these pages could prevent the comments asking about 1.18, and its fair to assume it hasnt been tested if these pages make no mention of 1.18 compatibility

**Comment by cerealcable** [comment]
@makcuber maintaining the multiple plugin listings for an established plugin such as Vault isn't necessary. If the websites that have Vault listed would like to verify the info they are welcome to do so, but Vault doesn't have upgrade issues since it's purpose is to be an additional abstraction layer for developers to allow flexibility and choices with a few kinds of items. As such an update to Minecraft is extremely unlikely to break it.

As such changing all of the listing sites is an effort that isn't going to give you value. Just use the plugin and enjoy the countless hours that have been given freely to the community.
