### ISSUE TITLE
"/vault-convert" seems to not work anymore

### ISSUE THREAD

**Issue by Folas1337** [MilkBowl/Vault#882]
By now I've probably tried about 6 different economy plugins and tried converting from one to another with no success at all.

Here's the procedure I go through:
> I give myself some money in one economy, shut down the server, install a second economy plugin, try converting, shut down the server again, remove the plugin I converted from and then start up the server once more but nothing ever gets converted.

I'm so confused why it just won't work :(

It's also not throwing any errors or giving me any useful information why it wouldn't work. I also want to add that I've never successfully done this before which means I don't even know if I'm doing it right at all but it shouldn't be that complicated.

Anyway, here's some more information:
> This server is running Paper version git-Paper-155 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 99cf01f)
You are running the latest version
Previous version: git-Paper-109 (MC: 1.18.1)
> iConomy 5.14
> Fe (Economy) 0.9
> XConomy 2.13.5
> The New Economy 0.1.1.16
> Vault 1.7.3

**Comment by Sleaker** [comment]
vault-convert is non-desctructive by design. This means that if you *ever* login to the server while both economies are installed then it probably wont work. vault-convert requires: hasAccount to return false in the target economy plugin for each account that is being converted. otherwise it will skip that account.
