### ISSUE TITLE
[Vault]: Loading Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}

### ISSUE THREAD

**Issue by AxlRose-RX** [MilkBowl/Vault#899]
Not really an issue, but is it supposed to show up like that on console?

[Vault]: Loading Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}

![image](https://user-images.githubusercontent.com/10159672/182236137-0a701b1f-f9ca-47db-a5f3-b1bb5dd6bb52.png)

Am I supposed to drop the 2 resulting .jars into the plugin folder or just the Vault-1.7.3.jar?

![image](https://user-images.githubusercontent.com/10159672/182236776-8d1d3de9-a422-4261-a7aa-8be3280bb887.png)

**Comment by cerealcable** [comment]
Was this build manually? Looks like an environment variable wasn't provided during build time thus resulting in the TRAVIS_BUILD_NUMBER string.

**Comment by AxlRose-RX** [comment]
I just used mvn to build it after cloning, was I supposed to provide some some extra arguments to mvn?

**Comment by cerealcable** [comment]
Yes, building outside of the build pipeline (travis) would mean you should expect some quirks. Shouldn't be too hard to provide a default variable of "snapshot" or something in it's place instead for local builds. Since this doesn't impact releases it's unlike we'll fix it but someone could open a PR if they wish.

**Comment by AxlRose-RX** [comment]
also what do I get on my server from using this up to date build instead of the Spigot one that has not been updated in 2 years?

**Comment by Jack1424** [comment]
You can see all of the changes made in the commit history.
