### ISSUE TITLE
Vault working on 1.19.2

### ISSUE THREAD

**Issue by r1sk01** [MilkBowl/Vault#902]
The plugin is running fine on 1.19.2 PaperMC

**Comment by MahoMuri** [comment]
Oh well then, thanks for that comment! Was about to ask about it HAHA

**Comment by lukebouch** [comment]
Is this plugin still being maintained?

**Comment by Jack1424** [comment]
The developers have been a little busy lately, but Vault should still function as well as it always has.

**Comment by lukebouch** [comment]
Thanks for the quick reply @Jack1424! I just installed it and it's still working with 1.19.2. It's been years since I used it but works flawlessly! I was just surprised to see it has been 2 years since the last release. 

I totally understand that everyone is busy and I really appreciate all the time and effort that has gone into it.
