### ISSUE TITLE
The latest version Vault1.7.3 has issues with papermc1.20.4

### ISSUE THREAD

**Issue by yuankun1** [MilkBowl/Vault#926]
When I only add the following three plugins
The CMI - 9.6.9.7
CMILib1.4.4.5
Vault - 1.7.3
My economy will be ineffective
And it doesn't matter if I give myself any amount of game money

When I opened the cmi inside the economy in the setting game coins must not exceed 1000 game coins without any message
Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  # Attention! For economy to work properly with other plugins you will need ether an injector or recompiled Vault version. 
  # You can find both option at top of plugins page
  # ATTENTION! If you disabled CMI economy while server was running, you will need to perform full server restart for this to take correct effect and avoid any issues while getting players balances
  Enabled: true
  # Determines if player needs to confirm money payment by clicking on chat message
  Confirmation: false
  # Set to true if you want to log money transfers between players
  LogEnabled: false

**Comment by Geolykt** [comment]
Hello, I'd report this to CMI (actually, please don't - but reporting it to them would've been more appropriate) since that message seems to be very vocal about it not being compatible with Vault out-of-the-box. Perhaps it's worth looking into what this message is talking about?

---

Why do you think that paper 1.20.4 is at fault here? Did you try it with older paper or spigot versions? It is generally adviseable to not fall to hasty conclusions here.

P.S.: Does anyone know why exactly CMI requires a patched version of Vault or this CMIInjector thingy? While understandable that sometimes compatibility patches are necessary it is a bit dubious to patch an API, especially since only one plugin can do that. My guess is that this is a workaround to plugins making use of the bad advice given in Vault's documentation when it comes to initializing the economy. Someone ought to fix that ASAP [I've wanted to do that myself for a while now, but I'm plainly too uninterested in minecraft as a whole nowadays].
